### ISSUE TITLE
Update Readme with some basic details

### ISSUE THREAD

**Issue by gokatz** [gokatz/ember-migration-helper#7]

**Comment by bartius-nigel** [comment]
Hi there!

I can do some updates for you. It looks like the main section introducing the app, a description of how to contribute and the deployment instructions are what is needed. Is that correct?

Can you please provide any current contribution instructions you have (Or I can add in a templated kind of thing) as well as which service provider you would want to deploy with?

**Comment by gokatz** [comment]
Thanks for picking this up @bartius-nigel. Had a look at your PR #8 and it looks cool.
